language: node_js
node_js:
- '4'
- '5'
- '6'
deploy:
  provider: npm
  email: sadorlovsky@gmail.com
  api_key:
    secure: iC5XRZPumvwbihPgF2u/Q+lFi4Ox2sfCfuEJz/ymtH8zpeoO1BR8A+REyAkOfJnRimfmLKCM09HvoFl7PLnUWdKK3b5Th9ndyrUQX95ZODi9HgARV1YPaZA8B92cShwJACvdoaA1+NNTFScyr4klnKUNvcbewdkoG3u3aqldN7Ef97JfQK7xn3MTYxI5HcSK9F6dT5UFik6DfS2/dbBFd7BSHZL+a0l5pSf/n+7zrVydRAqfvYuHUt/O/YWk7blZ7OE/fBQ+hNvXnKJexpO4PEB/ysHSCHVpfZuB0Gg7j4816Y0fBlgPsNwUQYPHvhZ55A1KvDshQMq49Lwoy+fowYJJrakpb982tyv0ZdhLCJDQPJcfVVf2KZ0h5uTwEw5ci+hYJMXpUBlv6Mtm0up1z9H2nABQTqm1G1uWf09NcAW1xSkjcsClL0dF11Bx0L2PcE0E8sUYAzxRSqZ/iS5ynEtW2DK2p7CQBrhOjEY3OYMNSsHxCwdVwunlqpLE2a/KN2h/TCJynfs427k8GA/E//xHT6khWYt5m+UcjdKCoDcw0Coamp4qDaoH3zlOwZx7N5MC0QrH3SN3dzxnCke0OCrgIYOKorwhP4200injQqZKE5YA97gA6oHezIiJVr5CphF7PNuEBSFruCJRzpfVBPEtW34KAH8jqEeCbVW6Uyk=
  on:
    tags: true
    repo: sadorlovsky/codestyle
